name: checkin
run-name: v2free-checkin

on: 
  schedule:
    - cron: 00 00 * * *
  push:

jobs:
  checkin:
    runs-on: ubuntu-latest
    env:
      AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58"
      TYPE: "Content-Type: application/json"
    steps:
      - name: Get cookies
        env:
          JSON: '{"email": "${{ vars.V2FREE_EMAIL }}", "passwd": "${{ secrets.V2FREE_PASSWORD }}"}'
        run: |
          curl -A $AGENT -c cookies -H $TYPE -d $JSON https://v2free.org/auth/login
        
      - name: Check in
        run: |
          curl -A $AGENT -X POST -b cookies -H $TYPE https://v2free.org/user/checkin