name: checkin
run-name: v2free-checkin

on: 
  schedule:
    - cron: 00 00 * * *
  push:

jobs:
  checkin:
    runs-on: ubuntu-latest
    env:
      AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58"
    steps:
      - name: Get cookies
        id: getCookies
        uses: fjogeleit/http-request-action@main
        with:
          url: https://v2free.org/auth/login
          method: POST
          data: "{email: ${{ secrets.V2FREE_EMAIL }}, passwd: ${{ secrets.V2FREE_PASSWORD }}}"
          customHeaders: "{Content-Type: application/json, User-Agent: ${{ env.AGENT }}}"
        
      - name: Check in
        uses: fjogeleit/http-request-action@main
        with:
          url: https://v2free.org/user/checkin
          method: POST
          data: ""
          customHeaders: "{Content-Type: application/json, User-Agent: ${{ env.AGENT }}, Cookie: ${{ join(fromJson(steps.getCookies.outputs.headers).set-cookie, ';') }}}"
